name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: sametustaoglu/samet-task

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker image build
        run: docker build -t $IMAGE_NAME:${GITHUB_SHA::7} .
      
      - name: docker image push
        run: docker push $IMAGE_NAME:${GITHUB_SHA::7}

