name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: sametustaoglu/samet-task

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker image build
        run: docker build -t $IMAGE_NAME:${GITHUB_SHA::7} .
      
      - name: docker image push
        run: docker push $IMAGE_NAME:${GITHUB_SHA::7}

  change_tag:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.TOKEN_GIT }}

      - name: change tag
        run: sed -i "s/samet-task:.*/samet-task:${GITHUB_SHA::7}/g" ./manifests/deployment.yaml

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: './manifests'
      

